### ISSUE TITLE
Non-existent IS function being called

### ISSUE THREAD

**Issue by ghost** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#1]
From [LambAdmin/Commands.cs:2946](https://github.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/blob/f1548ab55d4e3fc155046200a39c789b4a16561a/LambAdmin/Commands.cs#L2946)

``` c#
ent.Call("disableoffhandsecondaryweapons");
```

The function `disableoffhandsecondaryweapons` does not exist or is not at least added as a function by the script. This results in the error message:

```
[Function::Call] no such function: disableoffhandsecondaryweapons
```

**Comment by FredericaBernkastel** [comment]
Fixed by commit [38897b1](https://github.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/commit/38897b1f181064f6c3456c7f6465ce117c5b7efb).

#CLOSED.
