### ISSUE TITLE
Bug kicking players 

### ISSUE THREAD

**Issue by bossxxl** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#10]
when someone get kicked by script i get kicked with it 
[WriteLog::Info] # Player bryanzlr09 from group "default" connected.
[WriteLog::Info] # GUID: 76561201717347436 IP: 213.245.172.94:29644
[WriteLog::Info] # HWID: 00000000-00000000-00000000 ENTREF: 1
[WriteLog::Info] # XNADDR(12): 1300a8c0ff00
[WriteLog::Info] # Haxor connected. Could not retrieve/set player info. Kicking...
[SATm::I] Player bryanzlr09 left.
bryanzlr09 has been kicked.
[SATm::I] Player BOSS XXL SOLO left.
[SATm::I](Server now empty)
BOSS XXL SOLO has been kicked.

and i get an error Error! You are probably running Windows XP. This system is not compatible with TeknoMW3.

while im running windows 10 and why this happens?

**Comment by SymphonicDev** [comment]
[WriteLog::Info] # HWID: 00000000-00000000-00000000 ENTREF: 1   maybe because he has no hwid?

**Comment by bossxxl** [comment]
he got kicked for no HWID and me i have HWID i get kicked after he get kicked lol

**Comment by FredericaBernkastel** [comment]
> [SATm::I] Player bryanzlr09 left.

Man
You have SATm and DGAdmin loaded at same time. Server will be unstable, check configuration.

> and i get an error Error! You are probably running Windows XP

It's a Tekno's bug stories, not the script.

**Comment by FredericaBernkastel** [comment]
Also, looks like server cant retrieve HWID of client. Ordinary, it's a pattern of unbanner / cheats.

**Comment by bossxxl** [comment]
i did even dgadmin alone and did te same thing i think its teknogods bug but if i dont use dgadmin i dont get this problem i saw the script in dgadmin source of kicking can somone make building without kicking?
