### ISSUE TITLE
PermClantags

### ISSUE THREAD

**Issue by carck007** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#12]
Can you add a Permanent Clan tags 
i think its needed
ty

**Comment by FredericaBernkastel** [comment]
`CHANGED: !setclantag <player> [tag] -> !clantag <player> [tag]; `
Its saved permanently, like !alias (`Utils/forced_clantags.txt`)

Notice, that:
* Maximum length of tag - 7 characters;
* Command doesnt work, if clantag not set on the client side:
![](https://raw.githubusercontent.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/master/doc/img/000.png)

* Tag on the card is still limited to 4 chars:
![](https://raw.githubusercontent.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/master/doc/img/001.png)

**Comment by carck007** [comment]
Thank you its realy useful
