### ISSUE TITLE
Lockserver

### ISSUE THREAD

**Issue by carck007** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#13]
i want a (lockserver and unlockserver) commands , so i want when i play with my Clan members or a Friend and i dont want any one else to join the server i just need to type !lockserver so no one can join server till i unlocked the server with !unlockserver, those cmds needed at Clanwars or 1v1 match or Teamwars

**Comment by FredericaBernkastel** [comment]
`!lockserver`

First command execution -> write guids of connected players to "`Utils/guid_whitelist.txt`"
hook at "OnPlayerConnecting": drop all clients that not match whitelist
Second command execution -> remove whitelist, remove hook

thats easy

**Comment by FredericaBernkastel** [comment]
Sorry for being so slow. Waiting for issue #14 , because indication in the server list **MUST BE**

**Comment by carck007** [comment]
No. its okey take your time
