### ISSUE TITLE
Shared folder for more DGAdmin instances

### ISSUE THREAD

**Issue by weeder** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#15]
Hi 
First of all wanted to say you did good work with this plugin.
It has many things in one place what isn`t solved in similar plugins.It is firstly Lambder work ik.
But it doesnt matter.You continued the work and not stopped the development.
The only thing what is needed the shared folder for more servers.
So if someone have more servers, to have one main dgadmin folder where it store the info about players, admins, bans, etc...It is so complicated when some new member join the team, to go in all 6 servers to add him to admins, or even to remove him.As i understand the program it wont allow deleting/adding players while server run.Only when it is  #stopped 
Thanks in advance

**Comment by FredericaBernkastel** [comment]
I think, will be enough to make shared only these 3 files: `groups.txt`, `players.txt`, and `bannedplayers.txt`.

**Comment by FredericaBernkastel** [comment]
Also, i think, would be much easier to use hard links in your case.
I suppose, you know what is [NTFS Hard Link](https://en.wikipedia.org/wiki/Hard_link), and [how to make them](http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html).
Comment here, if it worked for you.

**Comment by FredericaBernkastel** [comment]
Btw shared settings will be possible only using SQLite database.
If i'll ever port DGAdmin to IS 1.5 and mono 3.5, and realize SQLite storage, i'll satisfy your request.

**Comment by weeder** [comment]
I solved it with hardlinks.I used the linux way with ln command.
Now i keep groups_autosave=false and hopefully the servers reload the new members when rotate the map.
The banlist anyway works fine.
Thx for clarify
