### ISSUE TITLE
GeoIP connect message and additional suggestions

### ISSUE THREAD

**Issue by yashrastogi** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#17]
Could you add GeoIP connect message support? You can host IP database on Github and disable the feature by default...
And could you please also add a functionality to disable custom team names/icons, add votemap, and add an option to list dsrs in /admin folder?

**Comment by FredericaBernkastel** [comment]
> add GeoIP connect message support

No, i wont realize this feature.

> disable custom team names/icons

Ye, i'll fix that.

> add an option to list dsrs in /admin folder

I'll add command `!dsrnames`, but for `/players2` folder.

**Comment by FredericaBernkastel** [comment]
Done.
Leave these settings empty to make them default
i.e
```
settings_teamnames_allies=
settings_teamnames_axis=
settings_teamicons_allies=
settings_teamicons_axis=
```
