### ISSUE TITLE
Vote kick?

### ISSUE THREAD

**Issue by DeadWeightt** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#2]
Hello @FredericaBernkastel 

Our clan uses your Admin plugin and it's great however i feel like it could be a bit improved with a new feature.

Vote kick, why? well, see, our admins can't be online 24/7 and so when they are offline there might be a hacker or two that's in the server and ruins the game for other players so this is where vote kick comes in.

Normal players / Clan Members can use this feature to kick out hackers.

Another great feature would be to add an alias to apply command so you could do @apply and it would broadcast it to the server and maybe do the same for xlrstats / xlrtopstats & Rules ? ;)

**Comment by SymphonicDev** [comment]
Testing this now in a simple modification of this but it will be !app for my servers

**Comment by SymphonicDev** [comment]
@DeadWeightt #6 

Global app command isnt exactly the command you wanted but it does work on my servers as !app .
you can msg me on discord if you got anymore ideas. (ill be looking into the votekick)

![b12a8ce295c010e5bdcd](https://cloud.githubusercontent.com/assets/4039146/15129100/7adda948-160d-11e6-88a8-b8a4eade564d.png)

**Comment by FredericaBernkastel** [comment]
Closed by commit [6acd573](https://github.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/commit/6acd573e096991fed94773c1e129d853b9a6529c).
