### ISSUE TITLE
VS?

### ISSUE THREAD

**Issue by mjordan1738** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#22]
Hi, r u using visual studio & if so what version u using to compile

**Comment by FredericaBernkastel** [comment]
Visual Studio 2015.
Target platform is .NET Framework 4.0

**Comment by mjordan1738** [comment]
Aight thx for ur reply
I have some issues compiling (debugging) the .cs files into one .dll file. Id have an idea if it's cause I'm using a different .NET Framework version (4.6) or just cause I ain't doing it right.

**Comment by mjordan1738** [comment]
I fixed my problem.
May I ask u about the infected mode.
I saw ur code & u made a string where u enabled the knife for infected. There's a problem about something considering the infected players. I think the lambadmin is overriding something in a .dsr file because the infected can't get anything like tactical insertion etc.. I found nothing in ur codes that were disabling that so may I ask u for ur help.

**Comment by FredericaBernkastel** [comment]
Maybe there?
https://github.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/blob/806f48e3f0c8d8f55f1b170054a55ae9459f7471/LambAdmin/ISnipe.cs#L201

**Comment by FredericaBernkastel** [comment]
You're playing infected with enabled `settings_isnipe` right?

**Comment by mjordan1738** [comment]
Yes

**Comment by mjordan1738** [comment]
I saw the code & u added tactical insertion but it doesn't show up in-game

**Comment by mjordan1738** [comment]
`            if (weapon == "iw5_usp45_mp_tactical" && Call<string>("getdvar", "g_gametype") == "infect" && attacker.GetTeam() != "allies")
                return;`
That should give me a tactical insertion right

**Comment by mjordan1738** [comment]
Is there no cmd to disable the isnipe mode in-game?

**Comment by FredericaBernkastel** [comment]
I realized [this feature](https://github.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/issues/18) a few days ago.
You can disable isnipe mode in `settings.txt`, then add to your iSnipe DSRs:
```
//#DGAdmin settings settings_isnipe=true
```
So isnipe mode will be enabled for isnipe DSRs, and disabled for reg guns.

**Comment by FredericaBernkastel** [comment]
The feature called «Dynamic Properties», you can override any DGAdmin setting from DSR.

**Comment by mjordan1738** [comment]
Aight ty

**Comment by mjordan1738** [comment]
"strictly disable feature in case of /admin folder exists"
Does that means that I will have to use the /players2 folder instead of the /admin folder?

**Comment by FredericaBernkastel** [comment]
Yes, use /players2

**Comment by mjordan1738** [comment]
`//#DGAdmin settings settings_isnipe=true`
Where am I supposed to put that (srry I'm beginner in C# coding)

**Comment by FredericaBernkastel** [comment]
In example, if you run server with `"sndisnipe.dsr"`,
put this string in the beginning of `"players2/sndisnipe.dsr"`
so isnipe mode will be enabled only for `sndisnipe.dsr`

**Comment by mjordan1738** [comment]
Oh ty

**Comment by mjordan1738** [comment]
Lol I mean in what file? Srry I'm so dumb

**Comment by FredericaBernkastel** [comment]
Nvm its broken now. Wait for v3.5 release.

**Comment by mjordan1738** [comment]
Ow I found it lol I'm so f*cking stupid srry
I didn't understand it first time becuz // meant a comment to me in C# but not in a dsr file lol

**Comment by FredericaBernkastel** [comment]
:Rubygasm:
