### ISSUE TITLE
DGAdmin :: PlayersFilter

### ISSUE THREAD

**Issue by FredericaBernkastel** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#23]
**Returns list of players based on selector.**
Multiple selectors are supported:

`selector1&selector2` = conjunction of selector1 and selector2
`selector1|selector2` = disjunction of selector1 and selector2

Conjunction and disjunction have same priority, i.e string is parsed from left to right.

`-selector` = complement of selector in U

**Selectors:**
 - `all`
 - `allies`
 - `enemies`
 - `team1` = axis
 - `team2` = allies
 - `spectators`
 - `alive`
 - `me` = sender
 - `name:` - specify directly part of player's name or clantag

**example:** 
`!kill *all&-me*`
`!kill *all&-name:bern*`
`!kill *enemies*`

**Comment by carck007** [comment]
This is usefull Neko
