### ISSUE TITLE
Miscounted play time (hours/mins)

### ISSUE THREAD

**Issue by yashrastogi** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#24]
DGAdmin shows 13 hours for all players at start of server and then increases over time and then resets when server is restarted to 13. Groups are also reset, including assigned players on reset.

**Comment by M3tropolo** [comment]
^^

**Comment by FredericaBernkastel** [comment]
I need to see your server config (`server.cfg`, `infinityscript.log`, list of files in `scripts/` folder).

**Comment by FredericaBernkastel** [comment]
Smoke weed every day. :sweat_drops:

**Comment by FredericaBernkastel** [comment]
Closed (not enough information to reproduce).
