### ISSUE TITLE
Another Suggestion!

### ISSUE THREAD

**Issue by DeadWeightt** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#7]
My friends and I were thinking how useful admin slots would be,

You could give admins (possibly clan members) (or whatever group you assign these slots to) slots
which will make those people in that particular group able to join the server when it's full, it would kick a person with the worst score in the server? or the one that's afk or spectating? also these slots wont be able to kick people in those groups that the slots are assigned to or groups like admins ?

Just a suggestion :)

**Comment by FredericaBernkastel** [comment]
`Looks interesting, and not so hard to implement. I'll think about it.`

**Comment by FredericaBernkastel** [comment]
seta sv_privateClients 2
Admin slots, huh
