### ISSUE TITLE
Few more commands/features that should be added (IMO)

### ISSUE THREAD

**Issue by DeadWeightt** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#8]
Hey man,

I love your plugin but i feel like it should have a ping kicker, 
what i mean by that is you should be able to set a limit on ping and if someone has a ping higher then the limit it would kick him for example; ping limit = 250 someone joins with ping 300 = gets kicked.

another feature/command that a lot of people would find helpful would be Vote cancel (forgot to mention this in votekick)

command; !votecancel or !vc for short and it would cancel the vote

permission for admins or the voter?

**Comment by FredericaBernkastel** [comment]
`Sorry, but project is nearly to be closed:
- It's incompatiple with incoming Tekno's InfinityScript v4.0 update
- I'm leaving Call of Duty forever

If you want, you can continue development, and can help with some things. But that's all.`

**Comment by DeadWeightt** [comment]
@FredericaBernkastel Hey! Is there anyway you could contact me on discord or maybe on skype?

Discord invite - http://discord.gg/012EiL5ImVJB3r1Zq
Skype username - facebook:kacper.luszczynski7

Thanks in advance,
DeadWeight
