### ISSUE TITLE
Bug/Error Report

### ISSUE THREAD

**Issue by DeadWeightt** [FredericaBernkastel/codmw3-server-DGAdmin-plugin#9]
Check this out please :+1: 

http://pastebin.com/kJxGNNRk

**Comment by FredericaBernkastel** [comment]
[/LambAdmin/Utilities.cs#L305](https://github.com/FredericaBernkastel/codmw3-server-DGAdmin-plugin/blob/0e5e679838fb7ac49058688dd84792cec8f3d47e/LambAdmin/Utilities.cs#L305)
kk
